### ISSUE TITLE
[Feature] Indefinite scenario practice

### ISSUE THREAD

**Issue by mavproductions** [zwolof/cs2-executes#16]
Hey guys,
Wondering how easy it would be to implement playing a particular scenario over and over. 

So if there's a particular execute (and specific util with that execute) it would be cool to have the option to replay it over and over to practice that specific scenario many times, until a player feels they had adequate practice.

Thanks for considering.

**Comment by ipsvn** [comment]
I've released this now :^)

**Comment by mavproductions** [comment]
Sweet Sweet ALL OFFICIAL BABY
